import { benzin, ego, tahoma } from '../styles/fonts'
import '../styles/globals.css'
import Providers from './providers'

export const metadata = {
  title: 'David Mamani - Portfolio',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

function RootLayout({ children }: Props) {
  return (
    <html lang='en' suppressHydrationWarning className={`${benzin.variable} ${ego.variable} ${tahoma.variable}`}>
      <body className='min-h-screen bg-white font-tahoma text-black dark:bg-black dark:text-white'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
